version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Get Current Account ID"
      - src_account_id=$(echo $CODEBUILD_BUILD_ARN | cut -d':' -f5)
      - echo "Logging in to the pre_build Amazon ECR in ..."
      - $(aws ecr get-login --no-include-email --registry-ids ${src_account_id} --region "us-east-2")
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Docker image..."
      - docker build -t demo-app .
      - docker tag 006455306600.dkr.ecr.us-east-2.amazonaws.com/demo-app-bobi:latest
  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push 006455306600.dkr.ecr.us-east-2.amazonaws.com/demo-app-bobi:latest